# Generated by Django 5.1.6 on 2025-02-27 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=45)),
                ('biografia', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'cadastro_autores',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^(?:\\d[\\ |-]?){13}$')])),
                ('edição', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('ano_publicação', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2027)])),
                ('preço_capa', models.FloatField()),
                ('categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cadastro_livros',
            },
        ),
        migrations.CreateModel(
            name='ControleEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('cadastro_livros', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.livros')),
            ],
            options={
                'db_table': 'controle_estoque',
                'unique_together': {('id', 'cadastro_livros')},
            },
        ),
        migrations.CreateModel(
            name='LivrosHasAutores',
            fields=[
                ('cadastro_livros', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.livros')),
                ('cadastro_autores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.autores')),
            ],
            options={
                'db_table': 'cadastro_livros_has_cadastro_autores',
                'unique_together': {('cadastro_livros', 'cadastro_autores')},
            },
        ),
    ]
