# Generated by Django 5.1.6 on 2025-02-22 01:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='ISBN inválido', regex='^(97(8|9))?\\d{9}(\\d|X)$')])),
                ('edicao', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2027)])),
                ('preco_capa', models.FloatField()),
                ('categoria', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cadastro_livros',
            },
        ),
        migrations.CreateModel(
            name='CadastroAutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('biografia', models.CharField(max_length=1000)),
                ('cadastro_livros', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.cadastrolivros')),
            ],
            options={
                'db_table': 'cadastro_autores',
                'unique_together': {('id', 'cadastro_livros')},
            },
        ),
        migrations.CreateModel(
            name='ControleEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_livros', models.IntegerField()),
                ('controle_estoquecol', models.IntegerField()),
                ('data_entrada_livro', models.DateField()),
                ('data_saida_livro', models.DateField()),
                ('cadastro_livros', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.cadastrolivros')),
            ],
            options={
                'db_table': 'controle_estoque',
                'unique_together': {('id', 'cadastro_livros')},
            },
        ),
    ]
