# Generated by Django 5.1.6 on 2025-02-22 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrolivros',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='ISBN inválido', regex='^(97(8|9))?-\\d{1,5}-\\d{1,7}-\\d{1,6}-\\d{1}$|^(97(8|9))?\\d{9}(\\d|X)$')]),
        ),
    ]
