# Generated by Django 5.1.6 on 2025-02-22 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cadastrolivros_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrolivros',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='ISBN inválido', regex='^(97(8|9))?-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,6}-[0-9]{1}$|^(97(8|9))?[0-9]{9}([0-9]|X)$')]),
        ),
    ]
