-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 16:17:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_estoque_papelaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_estoque_papelaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_estoque_papelaria` ;
USE `database_estoque_papelaria` ;

-- -----------------------------------------------------
-- Table `database_estoque_papelaria`.`cadastro_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_estoque_papelaria`.`cadastro_livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(17) NOT NULL,
  `edição` VARCHAR(255) NOT NULL,
  `editora` VARCHAR(255) NOT NULL,
  `ano_publicação` YEAR NOT NULL,
  `preço_capa` DOUBLE(10,2) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_estoque_papelaria`.`cadastro_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_estoque_papelaria`.`cadastro_autores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `biografia` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_estoque_papelaria`.`cadastro_livros_has_cadastro_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_estoque_papelaria`.`cadastro_livros_has_cadastro_autores` (
  `cadastro_livros_id` INT NOT NULL,
  `cadastro_autores_id` INT NOT NULL,
  PRIMARY KEY (`cadastro_livros_id`, `cadastro_autores_id`),
  INDEX `fk_cadastro_livros_has_cadastro_autores_cadastro_autores1_idx` (`cadastro_autores_id` ASC) VISIBLE,
  INDEX `fk_cadastro_livros_has_cadastro_autores_cadastro_livros_idx` (`cadastro_livros_id` ASC) VISIBLE,
  CONSTRAINT `fk_cadastro_livros_has_cadastro_autores_cadastro_livros`
    FOREIGN KEY (`cadastro_livros_id`)
    REFERENCES `database_estoque_papelaria`.`cadastro_livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cadastro_livros_has_cadastro_autores_cadastro_autores1`
    FOREIGN KEY (`cadastro_autores_id`)
    REFERENCES `database_estoque_papelaria`.`cadastro_autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_estoque_papelaria`.`controle_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_estoque_papelaria`.`controle_estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cadastro_livros_id` INT NOT NULL,
  `data_entrada` DATE NOT NULL,
  `data_saida` DATE NOT NULL,
  PRIMARY KEY (`id`, `cadastro_livros_id`),
  INDEX `fk_controle_estoque_cadastro_livros1_idx` (`cadastro_livros_id` ASC) VISIBLE,
  CONSTRAINT `fk_controle_estoque_cadastro_livros1`
    FOREIGN KEY (`cadastro_livros_id`)
    REFERENCES `database_estoque_papelaria`.`cadastro_livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
